### ISSUE TITLE
0x83 acc speed(mkz car)

### ISSUE THREAD

**Issue by woshikangfei** [ingenieroariel/abraham#58]
acc change speed
button +
current:083 00 00 00 00 00 00 00 00
changes:083 00 00 00 20 00 00 00 00

button -
current:083 00 00 00 00 00 00 00 00
changes:083 00 00 00 10 00 00 00 00

**Comment by eldarial** [comment]
is not this a duplicate of #10 ?

**Comment by ingenieroariel** [comment]
Yep, duplicate, closing this one.
